parameters:
    admin.emails: ['test@me.ru', 'test2@him.ua']
    email.send.from: 'noreply@insurance.com.ua'
    site.name: 'Страховое агенство "ПОЛИСМАРКЕТ"'
    site.domain: 'polismarket.com.ua'
    contact.email: 'sales@polismarket.com.ua'
    contact.phone: '(050) 001-01-01'
    savings: #show user fake money savings
        date.start: '30.07.2013' #initial date to start count
        initial.sum: 12345 #initial money amount
        increment: 23
    car.age.from: 1990
    displacement:
        min: 1.0
        max: 6.0
        step: 0.1
    insure.period: [0.5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    dgo.sum: [ 25000, 50000, 100000, 150000, 200000, 250000]
    ns.sum: [ 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000, 11000, 12000, 15000, 17000, 20000, 22000, 23000, 25000, 30000, 35000, 40000, 45000, 50000]
    passengers:
        min: 0
        max: 4
    base.rate: 180
