parameters:
    admin.emails: ['test@me.ru', 'test2@him.ua']
    email.send.from: 'noreply@insurance.com.ua'
    site.name: 'Страховое агенство "ПОЛИСМАРКЕТ"'
    site.domain: 'polismarket.com.ua'
    contact.email: 'sales@polismarket.com.ua'
    contact.phone: '(050) 001-01-01'
    savings: #show user fake money savings
        date.start: '30.07.2013' #initial date to start count
        initial.sum: 12345 #initial money amount
        increment: 23
    car.age.from: 1990
    displacement:
        min: 1.0
        max: 6.0
        step: 0.1
    insure.period: [0.5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 24, 36, 48, 60, 72, 84]
    dgo.sum: [ 50000, 100000, 150000, 200000, 250000]
    ns.sum: [ 5000, 10000, 25000, 50000]
    passengers:
        min: 0
        max: 4
    base.rate: 180 #Base rate for insurance calculation
    dgo.rate: 1.2 #Age rate
    timer: 10800 # in secs
    economy.sum: 103752 # initial sum for timer
    economy.step: 21 # step to increase once per 24 hours
    economy.startdate: 21.08.2013