insurance_content_homepage:
    pattern: /
    defaults: { _controller: InsuranceContentBundle:Default:index }
generate_polices:
    pattern: /admin/generate_polices
    defaults: { _controller: InsuranceContentBundle:Helper:generatePolicy }