insurance_content_homepage:
    pattern: /
    defaults: { _controller: InsuranceContentBundle:Default:index }
generate_polices:
    pattern: /admin/generate_polices
    defaults: { _controller: InsuranceContentBundle:Helper:generatePolicy }
mail_send:
    pattern: /notify
    defaults: { _controller: InsuranceContentBundle:Default:send }
generate_html_policy:
    pattern: /generate-html-policy/{orderId}
    defaults: { _controller: InsuranceContentBundle:Helper:generateHTMLPolicy }
generate_admin_notification:
    pattern: /generate-admin-notification/{feedback_id}
    defaults: { _controller: InsuranceContentBundle:PDF:notifyFeedback }
generate_pdf_policy:
    pattern: generate-pdf-policy/{orderId}
    defaults: { _controller: InsuranceContentBundle:PDF:generatePDFPolicy }
get_cities:
    pattern: /get-city.htm
    defaults: { _controller: InsuranceContentBundle:Default:getCities }
get_car_models:
    pattern: /get-car-model.htm
    defaults: { _controller: InsuranceContentBundle:Default:getCarModels }
calculate_go:
    pattern: /calculate.htm
    defaults: { _controller: InsuranceContentBundle:Default:goToStepOne }
    methods: [ 'POST' ]
feedback_create:
    pattern:  /create
    defaults: { _controller: "InsuranceContentBundle:Default:createFeedback" }
    requirements: { _method: POST }
step1:
    pattern: /step1.htm
    defaults: { _controller: InsuranceContentBundle:Default:calculator }
calculate_process:
    pattern: /save-calculator.htm
    defaults: { _controller: "InsuranceContentBundle:Default:processCalculator" }
    #methods: [ 'POST' ]
get_discount:
    pattern: /get-discount.htm
    defaults: { _controller: "InsuranceContentBundle:Default:getDiscount" }
    methods: [ 'POST' ]
step2:
    pattern: /step2.htm
    defaults: { _controller: "InsuranceContentBundle:Default:formalization"}
get_price:
    pattern: /get-price.htm
    defaults: { _controller: "InsuranceContentBundle:Default:calculateInsurance"}
    methods: [ 'POST' ]
get_dgo_price:
    pattern: /get-dgo-price.htm
    defaults: { _controller: "InsuranceContentBundle:Default:calculateDgo" }
    methods: [ 'POST' ]
get_ns_price:
    pattern: /get-ns-price.htm
    defaults: { _controller: "InsuranceContentBundle:Default:calculateNs" }
    methods: [ 'POST' ]
step3:
    pattern: /step3.htm
    defaults: { _controller: "InsuranceContentBundle:Default:delivery" }
save_calculation:
    pattern: /save-calculation.htm
    defaults: {_controller: "InsuranceContentBundle:Default:saveCalculation"}