insurance_content_homepage:
    pattern: /
    defaults: { _controller: InsuranceContentBundle:Default:index }
generate_polices:
    pattern: /admin/generate_polices
    defaults: { _controller: InsuranceContentBundle:Helper:generatePolicy }
mail_send:
    pattern: /notify
    defaults: { _controller: InsuranceContentBundle:Default:send }
generate_html_policy:
    pattern: /generate-html-policy/{orderId}
    defaults: { _controller: InsuranceContentBundle:Helper:generateHTMLPolicy }
generate_admin_notification:
    pattern: /generate-admin-notification/{feedback_id}
    defaults: { _controller: InsuranceContentBundle:PDF:notifyFeedback }
generate_pdf_policy:
    pattern: generate-pdf-policy/{orderId}
    defaults: { _controller: InsuranceContentBundle:PDF:generatePDFPolicy }
get_cities:
    pattern: /get-city
    defaults: { _controller: InsuranceContentBundle:Default:getCities }
get_car_models:
    pattern: /get-car-model
    defaults: { _controller: InsuranceContentBundle:Default:getCarModels }
calculate_go:
    pattern: /calculate
    defaults: { _controller: InsuranceContentBundle:Default:goToStepOne, method: POST }
step1:
    pattern: /step1.htm
    defaults: { _controller: InsuranceContentBundle:Default:stepOne }