parameters:
#    insurance_content.example.class: Insurance\ContentBundle\Example

services:
    insurance.content.admin.rate:
        class: Insurance\ContentBundle\Admin\RateAdmin
        arguments: [null, Insurance\ContentBundle\Entity\Rate, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Страхование', label: 'Коэффициенты' }
    insurance.content.admin.insuranceCompany:
        class: Insurance\ContentBundle\Admin\InsuranceCompanyAdmin
        arguments: [null, Insurance\ContentBundle\Entity\InsuranceCompany, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Страхование', label: 'Страховые компании' }
    insurance.content.admin.rateValue:
        class: Insurance\ContentBundle\Admin\RateValueAdmin
        arguments: [null, Insurance\ContentBundle\Entity\RateValue, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
    insurance.content.admin.companyRate:
        class: Insurance\ContentBundle\Admin\CompanyRateAdmin
        arguments: [null, Insurance\ContentBundle\Entity\CompanyRate, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Страхование', label: 'Коэффициенты компании' }
    insurance.content.admin.city:
        class: Insurance\ContentBundle\Admin\CityAdmin
        arguments: [null, Insurance\ContentBundle\Entity\City, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Регионы', label: 'Города' }
    insurance.content.admin.region:
        class: Insurance\ContentBundle\Admin\RegionAdmin
        arguments: [null, Insurance\ContentBundle\Entity\Region, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Регионы', label: 'Регионы' }
    insurance.content.admin.insuranceOrder:
        class: Insurance\ContentBundle\Admin\InsuranceOrderAdmin
        arguments: [null, Insurance\ContentBundle\Entity\InsuranceOrder, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Страхование', label: 'Заказы' }
    insurance.block.service.policy:
       class: Insurance\ContentBundle\Block\PolicyBlockService
       arguments: ['sonata.block.service.policy', '@templating']
       tags:
           - { name: sonata.block }