CarModel:
    type: entity
    table: car_model
    id:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    fields:
        value:
            type: string
            length: 30
            fixed: true
            nullable: false
    manyToOne:
        brand:
            targetEntity: CarBrand
            cascade: { delete }
            inversedBy: modelcar
            joinColumns:
                brand_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
