Policy:
    type: entity
    table: policy
    id:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    fields:
        value:
            type: string
            length: 20
            fixed: true
            nullable: false
        status:
            type: boolean
            nullable: false
    manyToOne:
        company:
            targetEntity: InsuranceCompany
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
