Rate:
    type: entity
    table: rate
    id:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    fields:
        value:
            type: string
            length: 50
            fixed: true
            nullable: false
        code:
            type: string
            length: 20
            fixed: true
            nullable: false
    lifecycleCallbacks: {  }
