RateValue:
    type: entity
    table: rate_value
    id:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    fields:
        value:
            type: string
            length: 100
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
